//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoYounder.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YOUNDEREntities : DbContext
    {
        public YOUNDEREntities()
            : base("name=YOUNDEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBEnderecoPessoaFisica> TBEnderecoPessoaFisica { get; set; }
        public virtual DbSet<TBPessoaFisica> TBPessoaFisica { get; set; }
        public virtual DbSet<TbSexo> TbSexo { get; set; }
    }
}
