//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoYounder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBPessoaFisica
    {
        public int idpessoafisica { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public byte Sexo { get; set; }
        public Nullable<long> Telefone { get; set; }
        public string email { get; set; }
    }
}
